/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as WaitingRouteImport } from './routes/waiting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRoute
  '/memory': typeof MemoryRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRoute
  '/waiting': typeof WaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRoute
  '/memory': typeof MemoryRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRoute
  '/waiting': typeof WaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRoute
  '/memory': typeof MemoryRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRoute
  '/waiting': typeof WaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/drafts'
    | '/inbox'
    | '/memory'
    | '/people'
    | '/planning'
    | '/settings'
    | '/teams'
    | '/tickets'
    | '/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/drafts'
    | '/inbox'
    | '/memory'
    | '/people'
    | '/planning'
    | '/settings'
    | '/teams'
    | '/tickets'
    | '/waiting'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/drafts'
    | '/inbox'
    | '/memory'
    | '/people'
    | '/planning'
    | '/settings'
    | '/teams'
    | '/tickets'
    | '/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DraftsRoute: typeof DraftsRoute
  InboxRoute: typeof InboxRoute
  MemoryRoute: typeof MemoryRoute
  PeopleRoute: typeof PeopleRoute
  PlanningRoute: typeof PlanningRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  TicketsRoute: typeof TicketsRoute
  WaitingRoute: typeof WaitingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DraftsRoute: DraftsRoute,
  InboxRoute: InboxRoute,
  MemoryRoute: MemoryRoute,
  PeopleRoute: PeopleRoute,
  PlanningRoute: PlanningRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  TicketsRoute: TicketsRoute,
  WaitingRoute: WaitingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
